In [54]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

Question 1

A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. 
A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level.
Please state the assumptions and tests that you carried out to check validity of the assumptions.


Solution: Conducting 2 tailed t-test on 2 independent samples
- let Null hypothesis(H0) = There is no significant difference between diameter of cutlet
- let Alternate hypothesis(H1) = There is a significant difference between diameter of cutlet

-Significance = 5%
therefore alpha = 0.05
As it is two tailed t test alpha = 0.025

Calculating t value:

In [3]:
data = pd.read_csv('C:/Users/hsang/Downloads/Cutlets.csv')

In [4]:
data.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [9]:
# checking for null values
data.isnull().sum()

Unit A    0
Unit B    0
dtype: int64

In [15]:
t_test, p_value = stats.ttest_ind(data['Unit A'], data['Unit B'],alternative='two-sided')

In [16]:
t_test

0.7228688704678063

In [18]:
p_value

0.4722394724599501

In [20]:
#Comparing pvalue with the aplha value
alpha = 0.025
if p_value<= alpha:
    print('We reject Null hyothesis there is significant difference between diameter of the cutlet')
else:
    print('We accept Null hypothesis there is not significant difference between diameter of the cutlet')

We accept Null hypothesis there is not significant difference between diameter of the cutlet


Question 2:

A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of 
reports of the laboratories on their preferred list.They collected a random sample and recorded TAT for 
reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

Solution:  As  the data has more than two independent groups so we will perform ANOVA test.
           
    Let Null hypothesis: There is no significant difference between the laboratories.
    Let Alternate Hypothesis: There is a significant difference between the laboratories.

    Calculating the ANOVA test: 
            


In [3]:
data1 = pd.read_csv('C:/Users/hsang/Downloads/LabTat.csv')

In [6]:
data1.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [7]:
# checking for null values
data1.isnull().sum()

Laboratory 1    0
Laboratory 2    0
Laboratory 3    0
Laboratory 4    0
dtype: int64

In [9]:
from scipy.stats import f_oneway

In [13]:
F_stats , pvalue = f_oneway(data1['Laboratory 1'],data1['Laboratory 2'],data1['Laboratory 3'], data1['Laboratory 4'])

In [14]:
F_stats

118.70421654401437

In [15]:
pvalue

2.1156708949992414e-57

In [16]:
alpha = 0.05
if pvalue<=alpha:
    print('We reject null hypothesis there is significant difference between average TAT of 4 laboratories')
else:
    print('We accpet null hypothesis there is not significant difference between average TAT of 4 laboratories')

We reject null hypothesis there is significant difference between average TAT of 4 laboratories


Question 3:
Sales of products in four different regions is tabulated for males and females. 
Find if male-female buyer rations are similar across regions.

Solution:  Using chi square test
     
    Let H0 = There is no association or dependency between the gender based buyer ratios
    Let H1 = There is  association or dependency between the gender based buyer ratios

    Calculating the Chi squre test for independence:-

In [36]:
data2 = pd.read_csv('C:/Users/hsang/Downloads/BuyerRatio.csv')
data2

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [39]:
data2 = data2[['East','West','North','South']]
data2

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [40]:
from scipy.stats import chi2_contingency

In [41]:
stat,p,dof,exp = stats.chi2_contingency(data2)

In [48]:
print('chi-sqaure: ',stat)
print('pvalue: ',p)
print('DOF: ',dof)
print('Expected values: ',exp)

chi-sqaure:  1.595945538661058
pvalue:  0.6603094907091882
DOF:  3
Expected values:  [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [49]:
Expected_values = exp

In [50]:
Expected_values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [58]:
observed = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])

In [59]:
observed

array([  50,  142,  131,   70,  435, 1523, 1356,  750])

In [60]:
expected = np.array([ 42.76531299,  146.81287862,  131.11756787,   72.30424052, 442.23468701, 1518.18712138, 1355.88243213,  747.69575948])

In [61]:
expected

array([  42.76531299,  146.81287862,  131.11756787,   72.30424052,
        442.23468701, 1518.18712138, 1355.88243213,  747.69575948])

In [63]:
from scipy.stats import chisquare
chi_stats , pvalue = chisquare(observed,expected,ddof = 3)

In [64]:
chi_stats

1.5959455390914483

In [65]:
pvalue

0.8095206646905712

In [66]:
alpha = 0.05
if pvalue <= alpha:
    print('We reject null hypothesis as  there is   association or dependency between the gender based buyer ratios ')
else:
    print('we accept null hypothesis as there is no association or dependency between the gender based buyer ratios')

we accept null hypothesis as there is no association or dependency between the gender based buyer ratios


Question 4:
TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms.
Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the 
defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.

Solution: Using chi square test

        Let H0: The defective % does not varies by centre.
        Let H1: The defective % varies by centre.

        Calculating chi-square test:-


In [67]:
data3 = pd.read_csv('C:/Users/hsang/Downloads/customer_order_form.csv')

In [68]:
data3

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [73]:
data3['Phillippines'].value_counts()

Phillippines
Error Free    271
Defective      29
Name: count, dtype: int64

In [74]:
data3['Indonesia'].value_counts()

Indonesia
Error Free    267
Defective      33
Name: count, dtype: int64

In [75]:
data3['Malta'].value_counts()

Malta
Error Free    269
Defective      31
Name: count, dtype: int64

In [76]:
data3['India'].value_counts()

India
Error Free    280
Defective      20
Name: count, dtype: int64

In [78]:
observed_values = ([[271,267,269,280],[29,33,31,20]])

In [86]:
observed = np.array([271,267,269,280,29,33,31,20])
observed

array([271, 267, 269, 280,  29,  33,  31,  20])

In [88]:
stats, p, dof, exp = chi2_contingency(observed_values)


In [90]:
print('stats: ',stats)
print('p: ',p)
print('dof: ',dof)
print('exp: ',exp)

stats:  3.858960685820355
p:  0.2771020991233135
dof:  3
exp:  [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [92]:
expected = np.array([271.75,271.75,271.75,271.75,28.25,28.25,28.25,28.25])
expected

array([271.75, 271.75, 271.75, 271.75,  28.25,  28.25,  28.25,  28.25])

In [93]:
chi_stats, pvalue = chisquare(observed,expected,ddof = 3)

In [94]:
chi_stats

3.858960685820355

In [95]:
pvalue

0.4254298144535761

In [97]:
alpha = 0.05
if pvalue<=alpha:
    print('We reject null hypothesis as  the defective % does  varies by centre')
else:
    print('we accept null hypothesis as the defective % does not varies by centre')

we accept null hypothesis as the defective % does not varies by centre
